
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 *
 */
import { sym_sl_elt } from "../base"
import type {
  SlAlert,
  SlAnimatedImage,
  SlBadge,
  SlAnimation,
  SlBreadcrumbItem,
  SlBreadcrumb,
  SlButton,
  SlAvatar,
  SlButtonGroup,
  SlCard,
  SlCheckbox,
  SlColorPicker,
  SlDetails,
  SlDialog,
  SlDivider,
  SlDrawer,
  SlDropdown,
  SlFormatBytes,
  SlFormatDate,
  SlFormatNumber,
  SlIcon,
  SlIconButton,
  SlImageComparer,
  SlInclude,
  SlInput,
  SlMenuItem,
  SlMenu,
  SlMenuLabel,
  SlMutationObserver,
  SlOption,
  SlPopup,
  SlProgressBar,
  SlProgressRing,
  SlQrCode,
  SlRadio,
  SlRadioButton,
  SlRadioGroup,
  SlRange,
  SlRating,
  SlRelativeTime,
  SlResizeObserver,
  SlSelect,
  SlSkeleton,
  SlSpinner,
  SlSplitPanel,
  SlSwitch,
  SlTab,
  SlTabGroup,
  SlTabPanel,
  SlTag,
  SlTextarea,
  SlTooltip,
  SlTree,
  SlTreeItem,
  SlVisuallyHidden,
} from "@shoelace-style/shoelace"


export function sl_is(node: Node, name: "sl-alert"): node is SlAlert
export function sl_is(node: Node, name: "sl-animated-image"): node is SlAnimatedImage
export function sl_is(node: Node, name: "sl-badge"): node is SlBadge
export function sl_is(node: Node, name: "sl-animation"): node is SlAnimation
export function sl_is(node: Node, name: "sl-breadcrumb-item"): node is SlBreadcrumbItem
export function sl_is(node: Node, name: "sl-breadcrumb"): node is SlBreadcrumb
export function sl_is(node: Node, name: "sl-button"): node is SlButton
export function sl_is(node: Node, name: "sl-avatar"): node is SlAvatar
export function sl_is(node: Node, name: "sl-button-group"): node is SlButtonGroup
export function sl_is(node: Node, name: "sl-card"): node is SlCard
export function sl_is(node: Node, name: "sl-checkbox"): node is SlCheckbox
export function sl_is(node: Node, name: "sl-color-picker"): node is SlColorPicker
export function sl_is(node: Node, name: "sl-details"): node is SlDetails
export function sl_is(node: Node, name: "sl-dialog"): node is SlDialog
export function sl_is(node: Node, name: "sl-divider"): node is SlDivider
export function sl_is(node: Node, name: "sl-drawer"): node is SlDrawer
export function sl_is(node: Node, name: "sl-dropdown"): node is SlDropdown
export function sl_is(node: Node, name: "sl-format-bytes"): node is SlFormatBytes
export function sl_is(node: Node, name: "sl-format-date"): node is SlFormatDate
export function sl_is(node: Node, name: "sl-format-number"): node is SlFormatNumber
export function sl_is(node: Node, name: "sl-icon"): node is SlIcon
export function sl_is(node: Node, name: "sl-icon-button"): node is SlIconButton
export function sl_is(node: Node, name: "sl-image-comparer"): node is SlImageComparer
export function sl_is(node: Node, name: "sl-include"): node is SlInclude
export function sl_is(node: Node, name: "sl-input"): node is SlInput
export function sl_is(node: Node, name: "sl-menu-item"): node is SlMenuItem
export function sl_is(node: Node, name: "sl-menu"): node is SlMenu
export function sl_is(node: Node, name: "sl-menu-label"): node is SlMenuLabel
export function sl_is(node: Node, name: "sl-mutation-observer"): node is SlMutationObserver
export function sl_is(node: Node, name: "sl-option"): node is SlOption
export function sl_is(node: Node, name: "sl-popup"): node is SlPopup
export function sl_is(node: Node, name: "sl-progress-bar"): node is SlProgressBar
export function sl_is(node: Node, name: "sl-progress-ring"): node is SlProgressRing
export function sl_is(node: Node, name: "sl-qr-code"): node is SlQrCode
export function sl_is(node: Node, name: "sl-radio"): node is SlRadio
export function sl_is(node: Node, name: "sl-radio-button"): node is SlRadioButton
export function sl_is(node: Node, name: "sl-radio-group"): node is SlRadioGroup
export function sl_is(node: Node, name: "sl-range"): node is SlRange
export function sl_is(node: Node, name: "sl-rating"): node is SlRating
export function sl_is(node: Node, name: "sl-relative-time"): node is SlRelativeTime
export function sl_is(node: Node, name: "sl-resize-observer"): node is SlResizeObserver
export function sl_is(node: Node, name: "sl-select"): node is SlSelect
export function sl_is(node: Node, name: "sl-skeleton"): node is SlSkeleton
export function sl_is(node: Node, name: "sl-spinner"): node is SlSpinner
export function sl_is(node: Node, name: "sl-split-panel"): node is SlSplitPanel
export function sl_is(node: Node, name: "sl-switch"): node is SlSwitch
export function sl_is(node: Node, name: "sl-tab"): node is SlTab
export function sl_is(node: Node, name: "sl-tab-group"): node is SlTabGroup
export function sl_is(node: Node, name: "sl-tab-panel"): node is SlTabPanel
export function sl_is(node: Node, name: "sl-tag"): node is SlTag
export function sl_is(node: Node, name: "sl-textarea"): node is SlTextarea
export function sl_is(node: Node, name: "sl-tooltip"): node is SlTooltip
export function sl_is(node: Node, name: "sl-tree"): node is SlTree
export function sl_is(node: Node, name: "sl-tree-item"): node is SlTreeItem
export function sl_is(node: Node, name: "sl-visually-hidden"): node is SlVisuallyHidden
export function sl_is(node: any, name: string): boolean {
  return node?.[sym_sl_elt] === name
}
