
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlAlert from "@shoelace-style/shoelace/dist/components/alert/alert.js"

export type {}
(SlAlert.prototype as any)[sym_sl_elt] = "sl-alert"

declare module "elt" {
  interface attrs_sl_alert extends Attrs<HTMLElementTagNameMap["sl-alert"]> {
    open?: NRO<boolean>
    closable?: NRO<boolean>
    variant?: NRO<'primary' | 'success' | 'neutral' | 'warning' | 'danger'>
    duration?: NRO<string>
  }

  interface ElementMap {
    "sl-alert": attrs_sl_alert
  }

}
