
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlAnimatedImage from "@shoelace-style/shoelace/dist/components/animated-image/animated-image.js"

export { SlAnimatedImage }
declare module "elt" {
  interface attrs_sl_animated_image extends Attrs<HTMLElementTagNameMap["sl-animated-image"]> {
    src?: NRO<string>
    alt?: NRO<string>
    play?: NRO<boolean>
  }

  interface ElementMap {
    "sl-animated-image": attrs_sl_animated_image
  }

}
