
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlAnimatedImage from "@shoelace-style/shoelace/dist/components/animated-image/animated-image.js"

export { SlAnimatedImage }
declare module "elt" {
  interface attrs_sl_animated_image extends Attrs<HTMLElementTagNameMap["sl-animated-image"]> {
    /** The path to the image to load. */
    src?: NRO<string>
    /** A description of the image used by assistive devices. */
    alt?: NRO<string>
    /** Plays the animation. When this attribute is remove, the animation will pause. */
    play?: NRO<boolean>
  }

  interface ElementMap {
    "sl-animated-image": attrs_sl_animated_image
  }

}
