
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlAnimation from "@shoelace-style/shoelace/dist/components/animation/animation.js"

export type {}
(SlAnimation.prototype as any)[sym_sl_elt] = "sl-animation"

declare module "elt" {
  interface attrs_sl_animation extends Attrs<HTMLElementTagNameMap["sl-animation"]>, Global {
    name?: NRO<string>
    play?: NRO<boolean>
    delay?: NRO<number>
    direction?: NRO<PlaybackDirection>
    duration?: NRO<number>
    easing?: NRO<string>
    "end-delay"?: NRO<number>
    fill?: NRO<FillMode>
    iterations?: NRO<string>
    "iteration-start"?: NRO<number>
    "playback-rate"?: NRO<number>
  }

  interface ElementMap {
    "sl-animation": attrs_sl_animation
  }

}
