
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlAvatar from "@shoelace-style/shoelace/dist/components/avatar/avatar.js"

export { SlAvatar }
declare module "elt" {
  interface attrs_sl_avatar extends Attrs<HTMLElementTagNameMap["sl-avatar"]> {
    image?: NRO<string>
    label?: NRO<string>
    initials?: NRO<string>
    loading?: NRO<'eager' | 'lazy'>
    shape?: NRO<'circle' | 'square' | 'rounded'>
  }

  interface ElementMap {
    "sl-avatar": attrs_sl_avatar
  }

}
