
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlBreadcrumbItem from "@shoelace-style/shoelace/dist/components/breadcrumb-item/breadcrumb-item.js"

export { SlBreadcrumbItem }
declare module "elt" {
  interface attrs_sl_breadcrumb_item extends Attrs<HTMLElementTagNameMap["sl-breadcrumb-item"]> {
    href?: NRO<string | undefined>
    target?: NRO<'_blank' | '_parent' | '_self' | '_top' | undefined>
    rel?: NRO<string>
  }

  interface ElementMap {
    "sl-breadcrumb-item": attrs_sl_breadcrumb_item
  }

}
