
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlBreadcrumb from "@shoelace-style/shoelace/dist/components/breadcrumb/breadcrumb.js"

export { SlBreadcrumb }
declare module "elt" {
  interface attrs_sl_breadcrumb extends Attrs<HTMLElementTagNameMap["sl-breadcrumb"]> {
    label?: NRO<string>
  }

  interface ElementMap {
    "sl-breadcrumb": attrs_sl_breadcrumb
  }

}
