
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlButton from "@shoelace-style/shoelace/dist/components/button/button.js"

export type {}
(SlButton.prototype as any)[sym_sl_elt] = "sl-button"

declare module "elt" {
  interface attrs_sl_button extends Attrs<HTMLElementTagNameMap["sl-button"]>, Global {
    title?: NRO<string>
    variant?: NRO<'default' | 'primary' | 'success' | 'neutral' | 'warning' | 'danger' | 'text'>
    size?: NRO<'small' | 'medium' | 'large'>
    caret?: NRO<boolean>
    disabled?: NRO<boolean>
    loading?: NRO<boolean>
    outline?: NRO<boolean>
    pill?: NRO<boolean>
    circle?: NRO<boolean>
    type?: NRO<'button' | 'submit' | 'reset'>
    name?: NRO<string>
    value?: NRO<string>
    href?: NRO<string>
    target?: NRO<'_blank' | '_parent' | '_self' | '_top'>
    download?: NRO<string | undefined>
    form?: NRO<string>
    formaction?: NRO<string>
    formenctype?: NRO<'application/x-www-form-urlencoded' | 'multipart/form-data' | 'text/plain'>
    formmethod?: NRO<'post' | 'get'>
    formnovalidate?: NRO<boolean>
    formtarget?: NRO<'_self' | '_blank' | '_parent' | '_top' | string>
  }

  interface ElementMap {
    "sl-button": attrs_sl_button
  }

}
