
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlButtonGroup from "@shoelace-style/shoelace/dist/components/button-group/button-group.js"

export { SlButtonGroup }
declare module "elt" {
  interface attrs_sl_button_group extends Attrs<HTMLElementTagNameMap["sl-button-group"]> {
    label?: NRO<string>
  }

  interface ElementMap {
    "sl-button-group": attrs_sl_button_group
  }

}
