
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlCard from "@shoelace-style/shoelace/dist/components/card/card.js"

export type {}
(SlCard.prototype as any)[sym_sl_elt] = "sl-card"

declare module "elt" {
  interface attrs_sl_card extends Attrs<HTMLElementTagNameMap["sl-card"]> {
  }

  interface ElementMap {
    "sl-card": attrs_sl_card
  }

}
