
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlCheckbox from "@shoelace-style/shoelace/dist/components/checkbox/checkbox.js"

export type {}
(SlCheckbox.prototype as any)[sym_sl_elt] = "sl-checkbox"

declare module "elt" {
  interface attrs_sl_checkbox extends Attrs<HTMLElementTagNameMap["sl-checkbox"]> {
    title?: NRO<string>
    name?: NRO<string>
    value?: NRO<string>
    size?: NRO<'small' | 'medium' | 'large'>
    disabled?: NRO<boolean>
    checked?: NRO<boolean>
    indeterminate?: NRO<boolean>
    form?: NRO<string>
    required?: NRO<boolean>
  }

  interface ElementMap {
    "sl-checkbox": attrs_sl_checkbox
  }

}
