
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlColorPicker from "@shoelace-style/shoelace/dist/components/color-picker/color-picker.js"

export type {}
(SlColorPicker.prototype as any)[sym_sl_elt] = "sl-color-picker"

declare module "elt" {
  interface attrs_sl_color_picker extends Attrs<HTMLElementTagNameMap["sl-color-picker"]> {
    value?: NRO<string>
    label?: NRO<string>
    format?: NRO<'hex' | 'rgb' | 'hsl' | 'hsv'>
    inline?: NRO<boolean>
    size?: NRO<'small' | 'medium' | 'large'>
    "no-format-toggle"?: NRO<boolean>
    name?: NRO<string>
    disabled?: NRO<boolean>
    hoist?: NRO<boolean>
    opacity?: NRO<boolean>
    uppercase?: NRO<boolean>
    swatches?: NRO<string | string[]>
    form?: NRO<string>
  }

  interface ElementMap {
    "sl-color-picker": attrs_sl_color_picker
  }

}
