
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlDivider from "@shoelace-style/shoelace/dist/components/divider/divider.js"

export type {}
(SlDivider.prototype as any)[sym_sl_elt] = "sl-divider"

declare module "elt" {
  interface attrs_sl_divider extends Attrs<HTMLElementTagNameMap["sl-divider"]> {
    vertical?: NRO<boolean>
  }

  interface ElementMap {
    "sl-divider": attrs_sl_divider
  }

}
