
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlDropdown from "@shoelace-style/shoelace/dist/components/dropdown/dropdown.js"

export type {}
(SlDropdown.prototype as any)[sym_sl_elt] = "sl-dropdown"

declare module "elt" {
  interface attrs_sl_dropdown extends Attrs<HTMLElementTagNameMap["sl-dropdown"]>, Global {
    open?: NRO<boolean>
    placement?: NRO<'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'right' | 'right-start' | 'right-end' | 'left' | 'left-start' | 'left-end'>
    disabled?: NRO<boolean>
    "stay-open-on-select"?: NRO<boolean>
    distance?: NRO<number>
    skidding?: NRO<number>
    hoist?: NRO<boolean>
  }

  interface ElementMap {
    "sl-dropdown": attrs_sl_dropdown
  }

}
