
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlFormatBytes from "@shoelace-style/shoelace/dist/components/format-bytes/format-bytes.js"

export { SlFormatBytes }
declare module "elt" {
  interface attrs_sl_format_bytes extends Attrs<HTMLElementTagNameMap["sl-format-bytes"]> {
    value?: NRO<number>
    unit?: NRO<'byte' | 'bit'>
    display?: NRO<'long' | 'short' | 'narrow'>
  }

  interface ElementMap {
    "sl-format-bytes": attrs_sl_format_bytes
  }

}
