
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlFormatDate from "@shoelace-style/shoelace/dist/components/format-date/format-date.js"

export { SlFormatDate }
declare module "elt" {
  interface attrs_sl_format_date extends Attrs<HTMLElementTagNameMap["sl-format-date"]> {
    date?: NRO<Date | string>
    weekday?: NRO<'narrow' | 'short' | 'long'>
    era?: NRO<'narrow' | 'short' | 'long'>
    year?: NRO<'numeric' | '2-digit'>
    month?: NRO<'numeric' | '2-digit' | 'narrow' | 'short' | 'long'>
    day?: NRO<'numeric' | '2-digit'>
    hour?: NRO<'numeric' | '2-digit'>
    minute?: NRO<'numeric' | '2-digit'>
    second?: NRO<'numeric' | '2-digit'>
    "time-zone-name"?: NRO<'short' | 'long'>
    "time-zone"?: NRO<string>
    "hour-format"?: NRO<'auto' | '12' | '24'>
  }

  interface ElementMap {
    "sl-format-date": attrs_sl_format_date
  }

}
