
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlFormatNumber from "@shoelace-style/shoelace/dist/components/format-number/format-number.js"

export { SlFormatNumber }
declare module "elt" {
  interface attrs_sl_format_number extends Attrs<HTMLElementTagNameMap["sl-format-number"]> {
    /** The number to format. */
    value?: NRO<number>
    /** The formatting style to use. */
    type?: NRO<'currency' | 'decimal' | 'percent'>
    /** Turns off grouping separators. */
    "no-grouping"?: NRO<boolean>
    /** The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code to use when formatting. */
    currency?: NRO<string>
    /** How to display the currency. */
    "currency-display"?: NRO<'symbol' | 'narrowSymbol' | 'code' | 'name'>
    /** The minimum number of integer digits to use. Possible values are 1-21. */
    "minimum-integer-digits"?: NRO<number>
    /** The minimum number of fraction digits to use. Possible values are 0-20. */
    "minimum-fraction-digits"?: NRO<number>
    /** The maximum number of fraction digits to use. Possible values are 0-0. */
    "maximum-fraction-digits"?: NRO<number>
    /** The minimum number of significant digits to use. Possible values are 1-21. */
    "minimum-significant-digits"?: NRO<number>
    /** The maximum number of significant digits to use,. Possible values are 1-21. */
    "maximum-significant-digits"?: NRO<number>
  }

  interface ElementMap {
    "sl-format-number": attrs_sl_format_number
  }

}
