
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlFormatNumber from "@shoelace-style/shoelace/dist/components/format-number/format-number.js"

export type {}
(SlFormatNumber.prototype as any)[sym_sl_elt] = "sl-format-number"

declare module "elt" {
  interface attrs_sl_format_number extends Attrs<HTMLElementTagNameMap["sl-format-number"]>, Global {
    value?: NRO<number>
    type?: NRO<'currency' | 'decimal' | 'percent'>
    "no-grouping"?: NRO<boolean>
    currency?: NRO<string>
    "currency-display"?: NRO<'symbol' | 'narrowSymbol' | 'code' | 'name'>
    "minimum-integer-digits"?: NRO<number>
    "minimum-fraction-digits"?: NRO<number>
    "maximum-fraction-digits"?: NRO<number>
    "minimum-significant-digits"?: NRO<number>
    "maximum-significant-digits"?: NRO<number>
  }

  interface ElementMap {
    "sl-format-number": attrs_sl_format_number
  }

}
