
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlIconButton from "@shoelace-style/shoelace/dist/components/icon-button/icon-button.js"

export { SlIconButton }
declare module "elt" {
  interface attrs_sl_icon_button extends Attrs<HTMLElementTagNameMap["sl-icon-button"]> {
    name?: NRO<string | undefined>
    library?: NRO<string | undefined>
    src?: NRO<string | undefined>
    href?: NRO<string | undefined>
    target?: NRO<'_blank' | '_parent' | '_self' | '_top' | undefined>
    download?: NRO<string | undefined>
    label?: NRO<string>
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-icon-button": attrs_sl_icon_button
  }

}
