
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlIcon from "@shoelace-style/shoelace/dist/components/icon/icon.js"

export type {}
(SlIcon.prototype as any)[sym_sl_elt] = "sl-icon"

declare module "elt" {
  interface attrs_sl_icon extends Attrs<HTMLElementTagNameMap["sl-icon"]>, Global {
    name?: NRO<string | undefined>
    src?: NRO<string | undefined>
    label?: NRO<string>
    library?: NRO<string>
  }

  interface ElementMap {
    "sl-icon": attrs_sl_icon
  }

}
