
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlIconButton from "@shoelace-style/shoelace/dist/components/icon-button/icon-button.js"

export { SlIconButton }
declare module "elt" {
  interface attrs_sl_icon_button extends Attrs<HTMLElementTagNameMap["sl-icon-button"]> {
    /** The name of the icon to draw. Available names depend on the icon library being used. */
    name?: NRO<string | undefined>
    /** The name of a registered custom icon library. */
    library?: NRO<string | undefined>
    /** An external URL of an SVG file. Be sure you trust the content you are including, as it will be executed as code and
can result in XSS attacks. */
    src?: NRO<string | undefined>
    /** When set, the underlying button will be rendered as an `<a>` with this `href` instead of a `<button>`. */
    href?: NRO<string | undefined>
    /** Tells the browser where to open the link. Only used when `href` is set. */
    target?: NRO<'_blank' | '_parent' | '_self' | '_top' | undefined>
    /** Tells the browser to download the linked file as this filename. Only used when `href` is set. */
    download?: NRO<string | undefined>
    /** A description that gets read by assistive devices. For optimal accessibility, you should always include a label
that describes what the icon button does. */
    label?: NRO<string>
    /** Disables the button. */
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-icon-button": attrs_sl_icon_button
  }

}
