
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlIcon from "@shoelace-style/shoelace/dist/components/icon/icon.js"

export { SlIcon }
declare module "elt" {
  interface attrs_sl_icon extends Attrs<HTMLElementTagNameMap["sl-icon"]> {
    name?: NRO<string | undefined>
    src?: NRO<string | undefined>
    label?: NRO<string>
    library?: NRO<string>
  }

  interface ElementMap {
    "sl-icon": attrs_sl_icon
  }

}
