
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlImageComparer from "@shoelace-style/shoelace/dist/components/image-comparer/image-comparer.js"

export type {}
(SlImageComparer.prototype as any)[sym_sl_elt] = "sl-image-comparer"

declare module "elt" {
  interface attrs_sl_image_comparer extends Attrs<HTMLElementTagNameMap["sl-image-comparer"]> {
    position?: NRO<number>
  }

  interface ElementMap {
    "sl-image-comparer": attrs_sl_image_comparer
  }

}
