
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlInclude from "@shoelace-style/shoelace/dist/components/include/include.js"

export type {}
(SlInclude.prototype as any)[sym_sl_elt] = "sl-include"

declare module "elt" {
  interface attrs_sl_include extends Attrs<HTMLElementTagNameMap["sl-include"]>, Global {
    src?: NRO<string>
    mode?: NRO<'cors' | 'no-cors' | 'same-origin'>
    "allow-scripts"?: NRO<boolean>
  }

  interface ElementMap {
    "sl-include": attrs_sl_include
  }

}
