
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlInclude from "@shoelace-style/shoelace/dist/components/include/include.js"

export { SlInclude }
declare module "elt" {
  interface attrs_sl_include extends Attrs<HTMLElementTagNameMap["sl-include"]> {
    src?: NRO<string>
    mode?: NRO<'cors' | 'no-cors' | 'same-origin'>
    "allow-scripts"?: NRO<boolean>
  }

  interface ElementMap {
    "sl-include": attrs_sl_include
  }

}
