
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlInput from "@shoelace-style/shoelace/dist/components/input/input.js"

export type {}
(SlInput.prototype as any)[sym_sl_elt] = "sl-input"

declare module "elt" {
  interface attrs_sl_input extends Attrs<HTMLElementTagNameMap["sl-input"]>, Global {
    title?: NRO<string>
    type?: NRO<'date' | 'datetime-local' | 'email' | 'number' | 'password' | 'search' | 'tel' | 'text' | 'time' | 'url'>
    name?: NRO<string>
    value?: NRO<string>
    size?: NRO<'small' | 'medium' | 'large'>
    filled?: NRO<boolean>
    pill?: NRO<boolean>
    label?: NRO<string>
    "help-text"?: NRO<string>
    clearable?: NRO<boolean>
    disabled?: NRO<boolean>
    placeholder?: NRO<string>
    readonly?: NRO<boolean>
    "password-toggle"?: NRO<boolean>
    "password-visible"?: NRO<boolean>
    "no-spin-buttons"?: NRO<boolean>
    form?: NRO<string>
    required?: NRO<boolean>
    pattern?: NRO<string>
    minlength?: NRO<number>
    maxlength?: NRO<number>
    min?: NRO<number>
    max?: NRO<number>
    step?: NRO<number | 'any'>
    autocapitalize?: NRO<'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters'>
    autocorrect?: NRO<'off' | 'on'>
    autocomplete?: NRO<string>
    autofocus?: NRO<boolean>
    enterkeyhint?: NRO<'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send'>
    spellcheck?: NRO<boolean>
    inputmode?: NRO<'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url'>
  }

  interface ElementMap {
    "sl-input": attrs_sl_input
  }

}
