
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlMenuItem from "@shoelace-style/shoelace/dist/components/menu-item/menu-item.js"

export { SlMenuItem }
declare module "elt" {
  interface attrs_sl_menu_item extends Attrs<HTMLElementTagNameMap["sl-menu-item"]> {
    type?: NRO<'normal' | 'checkbox'>
    checked?: NRO<boolean>
    value?: NRO<string>
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-menu-item": attrs_sl_menu_item
  }

}
