
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlMenuLabel from "@shoelace-style/shoelace/dist/components/menu-label/menu-label.js"

export type {}
(SlMenuLabel.prototype as any)[sym_sl_elt] = "sl-menu-label"

declare module "elt" {
  interface attrs_sl_menu_label extends Attrs<HTMLElementTagNameMap["sl-menu-label"]>, Global {
  }

  interface ElementMap {
    "sl-menu-label": attrs_sl_menu_label
  }

}
