
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlMenuLabel from "@shoelace-style/shoelace/dist/components/menu-label/menu-label.js"

export { SlMenuLabel }
declare module "elt" {
  interface attrs_sl_menu_label extends Attrs<HTMLElementTagNameMap["sl-menu-label"]> {
  }

  interface ElementMap {
    "sl-menu-label": attrs_sl_menu_label
  }

}
