
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlMenuItem from "@shoelace-style/shoelace/dist/components/menu-item/menu-item.js"

export type {}
(SlMenuItem.prototype as any)[sym_sl_elt] = "sl-menu-item"

declare module "elt" {
  interface attrs_sl_menu_item extends Attrs<HTMLElementTagNameMap["sl-menu-item"]>, Global {
    type?: NRO<'normal' | 'checkbox'>
    checked?: NRO<boolean>
    value?: NRO<string>
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-menu-item": attrs_sl_menu_item
  }

}
