
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlMutationObserver from "@shoelace-style/shoelace/dist/components/mutation-observer/mutation-observer.js"

export { SlMutationObserver }
declare module "elt" {
  interface attrs_sl_mutation_observer extends Attrs<HTMLElementTagNameMap["sl-mutation-observer"]> {
    attr?: NRO<string>
    "attr-old-value"?: NRO<boolean>
    "char-data"?: NRO<boolean>
    "char-data-old-value"?: NRO<boolean>
    "child-list"?: NRO<boolean>
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-mutation-observer": attrs_sl_mutation_observer
  }

}
