
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlOption from "@shoelace-style/shoelace/dist/components/option/option.js"

export { SlOption }
declare module "elt" {
  interface attrs_sl_option extends Attrs<HTMLElementTagNameMap["sl-option"]> {
    /** The option's value. When selected, the containing form control will receive this value. The value must be unique
from other options in the same group. Values may not contain spaces, as spaces are used as delimiters when listing
multiple values. */
    value?: NRO<string>
    /** Draws the option in a disabled state, preventing selection. */
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-option": attrs_sl_option
  }

}
