
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlOption from "@shoelace-style/shoelace/dist/components/option/option.js"

export { SlOption }
declare module "elt" {
  interface attrs_sl_option extends Attrs<HTMLElementTagNameMap["sl-option"]> {
    value?: NRO<string>
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-option": attrs_sl_option
  }

}
