
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlOption from "@shoelace-style/shoelace/dist/components/option/option.js"

export type {}
(SlOption.prototype as any)[sym_sl_elt] = "sl-option"

declare module "elt" {
  interface attrs_sl_option extends Attrs<HTMLElementTagNameMap["sl-option"]>, Global {
    value?: NRO<string>
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-option": attrs_sl_option
  }

}
