
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlPopup from "@shoelace-style/shoelace/dist/components/popup/popup.js"

export type {}
(SlPopup.prototype as any)[sym_sl_elt] = "sl-popup"

declare module "elt" {
  interface attrs_sl_popup extends Attrs<HTMLElementTagNameMap["sl-popup"]> {
    anchor?: NRO<Element | string>
    active?: NRO<boolean>
    placement?: NRO<'top' | 'top-start' | 'top-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'right' | 'right-start' | 'right-end' | 'left' | 'left-start' | 'left-end'>
    strategy?: NRO<'absolute' | 'fixed'>
    distance?: NRO<number>
    skidding?: NRO<number>
    arrow?: NRO<boolean>
    "arrow-placement"?: NRO<'start' | 'end' | 'center' | 'anchor'>
    "arrow-padding"?: NRO<number>
    flip?: NRO<boolean>
    "flip-fallback-placements"?: NRO<string>
    "flip-fallback-strategy"?: NRO<'best-fit' | 'initial'>
    flipBoundary?: NRO<Element | Element[]>
    "flip-padding"?: NRO<number>
    shift?: NRO<boolean>
    shiftBoundary?: NRO<Element | Element[]>
    "shift-padding"?: NRO<number>
    "auto-size"?: NRO<'horizontal' | 'vertical' | 'both'>
    sync?: NRO<'width' | 'height' | 'both'>
    autoSizeBoundary?: NRO<Element | Element[]>
    "auto-size-padding"?: NRO<number>
  }

  interface ElementMap {
    "sl-popup": attrs_sl_popup
  }

}
