
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlProgressRing from "@shoelace-style/shoelace/dist/components/progress-ring/progress-ring.js"

export type {}
(SlProgressRing.prototype as any)[sym_sl_elt] = "sl-progress-ring"

declare module "elt" {
  interface attrs_sl_progress_ring extends Attrs<HTMLElementTagNameMap["sl-progress-ring"]>, Global {
    value?: NRO<number>
    label?: NRO<string>
  }

  interface ElementMap {
    "sl-progress-ring": attrs_sl_progress_ring
  }

}
