
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlProgressBar from "@shoelace-style/shoelace/dist/components/progress-bar/progress-bar.js"

export type {}
(SlProgressBar.prototype as any)[sym_sl_elt] = "sl-progress-bar"

declare module "elt" {
  interface attrs_sl_progress_bar extends Attrs<HTMLElementTagNameMap["sl-progress-bar"]>, Global {
    value?: NRO<number>
    indeterminate?: NRO<boolean>
    label?: NRO<string>
  }

  interface ElementMap {
    "sl-progress-bar": attrs_sl_progress_bar
  }

}
