
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlProgressRing from "@shoelace-style/shoelace/dist/components/progress-ring/progress-ring.js"

export { SlProgressRing }
declare module "elt" {
  interface attrs_sl_progress_ring extends Attrs<HTMLElementTagNameMap["sl-progress-ring"]> {
    /** The current progress as a percentage, 0 to 100. */
    value?: NRO<number>
    /** A custom label for assistive devices. */
    label?: NRO<string>
  }

  interface ElementMap {
    "sl-progress-ring": attrs_sl_progress_ring
  }

}
