
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlRadioGroup from "@shoelace-style/shoelace/dist/components/radio-group/radio-group.js"

export type {}
(SlRadioGroup.prototype as any)[sym_sl_elt] = "sl-radio-group"

declare module "elt" {
  interface attrs_sl_radio_group extends Attrs<HTMLElementTagNameMap["sl-radio-group"]>, Global {
    label?: NRO<string>
    "help-text"?: NRO<string>
    name?: NRO<string>
    value?: NRO<string>
    form?: NRO<string>
    required?: NRO<boolean>
  }

  interface ElementMap {
    "sl-radio-group": attrs_sl_radio_group
  }

}
