
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlRadio from "@shoelace-style/shoelace/dist/components/radio/radio.js"

export { SlRadio }
declare module "elt" {
  interface attrs_sl_radio extends Attrs<HTMLElementTagNameMap["sl-radio"]> {
    /** The radio's value. When selected, the radio group will receive this value. */
    value?: NRO<string>
    /** The radio's size. When used inside a radio group, the size will be determined by the radio group's size so this
attribute can typically be omitted. */
    size?: NRO<'small' | 'medium' | 'large'>
    /** Disables the radio. */
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-radio": attrs_sl_radio
  }

}
