
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlRange from "@shoelace-style/shoelace/dist/components/range/range.js"

export { SlRange }
declare module "elt" {
  interface attrs_sl_range extends Attrs<HTMLElementTagNameMap["sl-range"]> {
    title?: NRO<string>
    name?: NRO<string>
    value?: NRO<number>
    label?: NRO<string>
    "help-text"?: NRO<string>
    disabled?: NRO<boolean>
    min?: NRO<number>
    max?: NRO<number>
    step?: NRO<number>
    tooltip?: NRO<'top' | 'bottom' | 'none'>
    form?: NRO<string>
  }

  interface ElementMap {
    "sl-range": attrs_sl_range
  }

}
