
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlRating from "@shoelace-style/shoelace/dist/components/rating/rating.js"

export type {}
(SlRating.prototype as any)[sym_sl_elt] = "sl-rating"

declare module "elt" {
  interface attrs_sl_rating extends Attrs<HTMLElementTagNameMap["sl-rating"]>, Global {
    label?: NRO<string>
    value?: NRO<number>
    max?: NRO<number>
    precision?: NRO<number>
    readonly?: NRO<boolean>
    disabled?: NRO<boolean>
    getSymbol?: NRO<(value: number) => string>
  }

  interface ElementMap {
    "sl-rating": attrs_sl_rating
  }

}
