
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlRelativeTime from "@shoelace-style/shoelace/dist/components/relative-time/relative-time.js"

export { SlRelativeTime }
declare module "elt" {
  interface attrs_sl_relative_time extends Attrs<HTMLElementTagNameMap["sl-relative-time"]> {
    date?: NRO<Date | string>
    format?: NRO<'long' | 'short' | 'narrow'>
    numeric?: NRO<'always' | 'auto'>
    sync?: NRO<boolean>
  }

  interface ElementMap {
    "sl-relative-time": attrs_sl_relative_time
  }

}
