
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlResizeObserver from "@shoelace-style/shoelace/dist/components/resize-observer/resize-observer.js"

export { SlResizeObserver }
declare module "elt" {
  interface attrs_sl_resize_observer extends Attrs<HTMLElementTagNameMap["sl-resize-observer"]> {
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-resize-observer": attrs_sl_resize_observer
  }

}
