
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlResizeObserver from "@shoelace-style/shoelace/dist/components/resize-observer/resize-observer.js"

export type {}
(SlResizeObserver.prototype as any)[sym_sl_elt] = "sl-resize-observer"

declare module "elt" {
  interface attrs_sl_resize_observer extends Attrs<HTMLElementTagNameMap["sl-resize-observer"]> {
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-resize-observer": attrs_sl_resize_observer
  }

}
