
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlSpinner from "@shoelace-style/shoelace/dist/components/spinner/spinner.js"

export type {}
(SlSpinner.prototype as any)[sym_sl_elt] = "sl-spinner"

declare module "elt" {
  interface attrs_sl_spinner extends Attrs<HTMLElementTagNameMap["sl-spinner"]>, Global {
  }

  interface ElementMap {
    "sl-spinner": attrs_sl_spinner
  }

}
