
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlSwitch from "@shoelace-style/shoelace/dist/components/switch/switch.js"

export type {}
(SlSwitch.prototype as any)[sym_sl_elt] = "sl-switch"

declare module "elt" {
  interface attrs_sl_switch extends Attrs<HTMLElementTagNameMap["sl-switch"]>, Global {
    title?: NRO<string>
    name?: NRO<string>
    value?: NRO<string>
    size?: NRO<'small' | 'medium' | 'large'>
    disabled?: NRO<boolean>
    checked?: NRO<boolean>
    form?: NRO<string>
    required?: NRO<boolean>
  }

  interface ElementMap {
    "sl-switch": attrs_sl_switch
  }

}
