
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlSwitch from "@shoelace-style/shoelace/dist/components/switch/switch.js"

export { SlSwitch }
declare module "elt" {
  interface attrs_sl_switch extends Attrs<HTMLElementTagNameMap["sl-switch"]> {
    title?: NRO<string>
    name?: NRO<string>
    value?: NRO<string>
    size?: NRO<'small' | 'medium' | 'large'>
    disabled?: NRO<boolean>
    checked?: NRO<boolean>
    form?: NRO<string>
    required?: NRO<boolean>
  }

  interface ElementMap {
    "sl-switch": attrs_sl_switch
  }

}
