
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlTabPanel from "@shoelace-style/shoelace/dist/components/tab-panel/tab-panel.js"

export { SlTabPanel }
declare module "elt" {
  interface attrs_sl_tab_panel extends Attrs<HTMLElementTagNameMap["sl-tab-panel"]> {
    name?: NRO<string>
    active?: NRO<boolean>
  }

  interface ElementMap {
    "sl-tab-panel": attrs_sl_tab_panel
  }

}
