
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlTabPanel from "@shoelace-style/shoelace/dist/components/tab-panel/tab-panel.js"

export { SlTabPanel }
declare module "elt" {
  interface attrs_sl_tab_panel extends Attrs<HTMLElementTagNameMap["sl-tab-panel"]> {
    /** The tab panel's name. */
    name?: NRO<string>
    /** When true, the tab panel will be shown. */
    active?: NRO<boolean>
  }

  interface ElementMap {
    "sl-tab-panel": attrs_sl_tab_panel
  }

}
