
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlTab from "@shoelace-style/shoelace/dist/components/tab/tab.js"

export type {}
(SlTab.prototype as any)[sym_sl_elt] = "sl-tab"

declare module "elt" {
  interface attrs_sl_tab extends Attrs<HTMLElementTagNameMap["sl-tab"]>, Global {
    panel?: NRO<string>
    active?: NRO<boolean>
    closable?: NRO<boolean>
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-tab": attrs_sl_tab
  }

}
