
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlTab from "@shoelace-style/shoelace/dist/components/tab/tab.js"

export { SlTab }
declare module "elt" {
  interface attrs_sl_tab extends Attrs<HTMLElementTagNameMap["sl-tab"]> {
    panel?: NRO<string>
    active?: NRO<boolean>
    closable?: NRO<boolean>
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-tab": attrs_sl_tab
  }

}
