
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlTag from "@shoelace-style/shoelace/dist/components/tag/tag.js"

export type {}
(SlTag.prototype as any)[sym_sl_elt] = "sl-tag"

declare module "elt" {
  interface attrs_sl_tag extends Attrs<HTMLElementTagNameMap["sl-tag"]> {
    variant?: NRO<'primary' | 'success' | 'neutral' | 'warning' | 'danger' | 'text'>
    size?: NRO<'small' | 'medium' | 'large'>
    pill?: NRO<boolean>
    removable?: NRO<boolean>
  }

  interface ElementMap {
    "sl-tag": attrs_sl_tag
  }

}
