
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlTextarea from "@shoelace-style/shoelace/dist/components/textarea/textarea.js"

export { SlTextarea }
declare module "elt" {
  interface attrs_sl_textarea extends Attrs<HTMLElementTagNameMap["sl-textarea"]> {
    title?: NRO<string>
    name?: NRO<string>
    value?: NRO<string>
    size?: NRO<'small' | 'medium' | 'large'>
    filled?: NRO<boolean>
    label?: NRO<string>
    "help-text"?: NRO<string>
    placeholder?: NRO<string>
    rows?: NRO<number>
    resize?: NRO<'none' | 'vertical' | 'auto'>
    disabled?: NRO<boolean>
    readonly?: NRO<boolean>
    form?: NRO<string>
    required?: NRO<boolean>
    minlength?: NRO<number>
    maxlength?: NRO<number>
    autocapitalize?: NRO<'off' | 'none' | 'on' | 'sentences' | 'words' | 'characters'>
    autocorrect?: NRO<string>
    autocomplete?: NRO<string>
    autofocus?: NRO<boolean>
    enterkeyhint?: NRO<'enter' | 'done' | 'go' | 'next' | 'previous' | 'search' | 'send'>
    spellcheck?: NRO<boolean>
    inputmode?: NRO<'none' | 'text' | 'decimal' | 'numeric' | 'tel' | 'search' | 'email' | 'url'>
  }

  interface ElementMap {
    "sl-textarea": attrs_sl_textarea
  }

}
