
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlTooltip from "@shoelace-style/shoelace/dist/components/tooltip/tooltip.js"

export { SlTooltip }
declare module "elt" {
  interface attrs_sl_tooltip extends Attrs<HTMLElementTagNameMap["sl-tooltip"]> {
    content?: NRO<string>
    placement?: NRO<'top' | 'top-start' | 'top-end' | 'right' | 'right-start' | 'right-end' | 'bottom' | 'bottom-start' | 'bottom-end' | 'left' | 'left-start' | 'left-end'>
    disabled?: NRO<boolean>
    distance?: NRO<number>
    open?: NRO<boolean>
    skidding?: NRO<number>
    trigger?: NRO<string>
    hoist?: NRO<boolean>
  }

  interface ElementMap {
    "sl-tooltip": attrs_sl_tooltip
  }

}
