
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlTree from "@shoelace-style/shoelace/dist/components/tree/tree.js"

export { SlTree }
declare module "elt" {
  interface attrs_sl_tree extends Attrs<HTMLElementTagNameMap["sl-tree"]> {
    selection?: NRO<'single' | 'multiple' | 'leaf'>
  }

  interface ElementMap {
    "sl-tree": attrs_sl_tree
  }

}
