
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import { sym_sl_elt } from "../base"

import SlTreeItem from "@shoelace-style/shoelace/dist/components/tree-item/tree-item.js"

export type {}
(SlTreeItem.prototype as any)[sym_sl_elt] = "sl-tree-item"

declare module "elt" {
  interface attrs_sl_tree_item extends Attrs<HTMLElementTagNameMap["sl-tree-item"]> {
    expanded?: NRO<boolean>
    selected?: NRO<boolean>
    disabled?: NRO<boolean>
    lazy?: NRO<boolean>
  }

  interface ElementMap {
    "sl-tree-item": attrs_sl_tree_item
  }

}
