
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 *
 */
import type {
  SlAlert,
  SlAnimatedImage,
  SlBadge,
  SlBreadcrumb,
  SlBreadcrumbItem,
  SlAnimation,
  SlButton,
  SlAvatar,
  SlButtonGroup,
  SlCard,
  SlCarousel,
  SlCarouselItem,
  SlCheckbox,
  SlColorPicker,
  SlCopyButton,
  SlDetails,
  SlDialog,
  SlDivider,
  SlDrawer,
  SlDropdown,
  SlFormatBytes,
  SlFormatDate,
  SlFormatNumber,
  SlIcon,
  SlIconButton,
  SlImageComparer,
  SlInclude,
  SlInput,
  SlMenu,
  SlMenuItem,
  SlMenuLabel,
  SlMutationObserver,
  SlOption,
  SlPopup,
  SlProgressRing,
  SlRadio,
  SlQrCode,
  SlRange,
  SlRadioGroup,
  SlProgressBar,
  SlRadioButton,
  SlRating,
  SlRelativeTime,
  SlResizeObserver,
  SlSelect,
  SlSkeleton,
  SlSpinner,
  SlSplitPanel,
  SlSwitch,
  SlTab,
  SlTabPanel,
  SlTabGroup,
  SlTooltip,
  SlTree,
  SlTextarea,
  SlTag,
  SlTreeItem,
  SlVisuallyHidden,
} from "@shoelace-style/shoelace"


export type SlElement = 
  | SlAlert & { tagName: "SL-ALERT" }
  | SlAnimatedImage & { tagName: "SL-ANIMATED-IMAGE" }
  | SlBadge & { tagName: "SL-BADGE" }
  | SlBreadcrumb & { tagName: "SL-BREADCRUMB" }
  | SlBreadcrumbItem & { tagName: "SL-BREADCRUMB-ITEM" }
  | SlAnimation & { tagName: "SL-ANIMATION" }
  | SlButton & { tagName: "SL-BUTTON" }
  | SlAvatar & { tagName: "SL-AVATAR" }
  | SlButtonGroup & { tagName: "SL-BUTTON-GROUP" }
  | SlCard & { tagName: "SL-CARD" }
  | SlCarousel & { tagName: "SL-CAROUSEL" }
  | SlCarouselItem & { tagName: "SL-CAROUSEL-ITEM" }
  | SlCheckbox & { tagName: "SL-CHECKBOX" }
  | SlColorPicker & { tagName: "SL-COLOR-PICKER" }
  | SlCopyButton & { tagName: "SL-COPY-BUTTON" }
  | SlDetails & { tagName: "SL-DETAILS" }
  | SlDialog & { tagName: "SL-DIALOG" }
  | SlDivider & { tagName: "SL-DIVIDER" }
  | SlDrawer & { tagName: "SL-DRAWER" }
  | SlDropdown & { tagName: "SL-DROPDOWN" }
  | SlFormatBytes & { tagName: "SL-FORMAT-BYTES" }
  | SlFormatDate & { tagName: "SL-FORMAT-DATE" }
  | SlFormatNumber & { tagName: "SL-FORMAT-NUMBER" }
  | SlIcon & { tagName: "SL-ICON" }
  | SlIconButton & { tagName: "SL-ICON-BUTTON" }
  | SlImageComparer & { tagName: "SL-IMAGE-COMPARER" }
  | SlInclude & { tagName: "SL-INCLUDE" }
  | SlInput & { tagName: "SL-INPUT" }
  | SlMenu & { tagName: "SL-MENU" }
  | SlMenuItem & { tagName: "SL-MENU-ITEM" }
  | SlMenuLabel & { tagName: "SL-MENU-LABEL" }
  | SlMutationObserver & { tagName: "SL-MUTATION-OBSERVER" }
  | SlOption & { tagName: "SL-OPTION" }
  | SlPopup & { tagName: "SL-POPUP" }
  | SlProgressRing & { tagName: "SL-PROGRESS-RING" }
  | SlRadio & { tagName: "SL-RADIO" }
  | SlQrCode & { tagName: "SL-QR-CODE" }
  | SlRange & { tagName: "SL-RANGE" }
  | SlRadioGroup & { tagName: "SL-RADIO-GROUP" }
  | SlProgressBar & { tagName: "SL-PROGRESS-BAR" }
  | SlRadioButton & { tagName: "SL-RADIO-BUTTON" }
  | SlRating & { tagName: "SL-RATING" }
  | SlRelativeTime & { tagName: "SL-RELATIVE-TIME" }
  | SlResizeObserver & { tagName: "SL-RESIZE-OBSERVER" }
  | SlSelect & { tagName: "SL-SELECT" }
  | SlSkeleton & { tagName: "SL-SKELETON" }
  | SlSpinner & { tagName: "SL-SPINNER" }
  | SlSplitPanel & { tagName: "SL-SPLIT-PANEL" }
  | SlSwitch & { tagName: "SL-SWITCH" }
  | SlTab & { tagName: "SL-TAB" }
  | SlTabPanel & { tagName: "SL-TAB-PANEL" }
  | SlTabGroup & { tagName: "SL-TAB-GROUP" }
  | SlTooltip & { tagName: "SL-TOOLTIP" }
  | SlTree & { tagName: "SL-TREE" }
  | SlTextarea & { tagName: "SL-TEXTAREA" }
  | SlTag & { tagName: "SL-TAG" }
  | SlTreeItem & { tagName: "SL-TREE-ITEM" }
  | SlVisuallyHidden & { tagName: "SL-VISUALLY-HIDDEN" }


export function sl_is(node: Element, name: "SL-ALERT"): node is SlAlert
export function sl_is(node: Element, name: "SL-ANIMATED-IMAGE"): node is SlAnimatedImage
export function sl_is(node: Element, name: "SL-BADGE"): node is SlBadge
export function sl_is(node: Element, name: "SL-BREADCRUMB"): node is SlBreadcrumb
export function sl_is(node: Element, name: "SL-BREADCRUMB-ITEM"): node is SlBreadcrumbItem
export function sl_is(node: Element, name: "SL-ANIMATION"): node is SlAnimation
export function sl_is(node: Element, name: "SL-BUTTON"): node is SlButton
export function sl_is(node: Element, name: "SL-AVATAR"): node is SlAvatar
export function sl_is(node: Element, name: "SL-BUTTON-GROUP"): node is SlButtonGroup
export function sl_is(node: Element, name: "SL-CARD"): node is SlCard
export function sl_is(node: Element, name: "SL-CAROUSEL"): node is SlCarousel
export function sl_is(node: Element, name: "SL-CAROUSEL-ITEM"): node is SlCarouselItem
export function sl_is(node: Element, name: "SL-CHECKBOX"): node is SlCheckbox
export function sl_is(node: Element, name: "SL-COLOR-PICKER"): node is SlColorPicker
export function sl_is(node: Element, name: "SL-COPY-BUTTON"): node is SlCopyButton
export function sl_is(node: Element, name: "SL-DETAILS"): node is SlDetails
export function sl_is(node: Element, name: "SL-DIALOG"): node is SlDialog
export function sl_is(node: Element, name: "SL-DIVIDER"): node is SlDivider
export function sl_is(node: Element, name: "SL-DRAWER"): node is SlDrawer
export function sl_is(node: Element, name: "SL-DROPDOWN"): node is SlDropdown
export function sl_is(node: Element, name: "SL-FORMAT-BYTES"): node is SlFormatBytes
export function sl_is(node: Element, name: "SL-FORMAT-DATE"): node is SlFormatDate
export function sl_is(node: Element, name: "SL-FORMAT-NUMBER"): node is SlFormatNumber
export function sl_is(node: Element, name: "SL-ICON"): node is SlIcon
export function sl_is(node: Element, name: "SL-ICON-BUTTON"): node is SlIconButton
export function sl_is(node: Element, name: "SL-IMAGE-COMPARER"): node is SlImageComparer
export function sl_is(node: Element, name: "SL-INCLUDE"): node is SlInclude
export function sl_is(node: Element, name: "SL-INPUT"): node is SlInput
export function sl_is(node: Element, name: "SL-MENU"): node is SlMenu
export function sl_is(node: Element, name: "SL-MENU-ITEM"): node is SlMenuItem
export function sl_is(node: Element, name: "SL-MENU-LABEL"): node is SlMenuLabel
export function sl_is(node: Element, name: "SL-MUTATION-OBSERVER"): node is SlMutationObserver
export function sl_is(node: Element, name: "SL-OPTION"): node is SlOption
export function sl_is(node: Element, name: "SL-POPUP"): node is SlPopup
export function sl_is(node: Element, name: "SL-PROGRESS-RING"): node is SlProgressRing
export function sl_is(node: Element, name: "SL-RADIO"): node is SlRadio
export function sl_is(node: Element, name: "SL-QR-CODE"): node is SlQrCode
export function sl_is(node: Element, name: "SL-RANGE"): node is SlRange
export function sl_is(node: Element, name: "SL-RADIO-GROUP"): node is SlRadioGroup
export function sl_is(node: Element, name: "SL-PROGRESS-BAR"): node is SlProgressBar
export function sl_is(node: Element, name: "SL-RADIO-BUTTON"): node is SlRadioButton
export function sl_is(node: Element, name: "SL-RATING"): node is SlRating
export function sl_is(node: Element, name: "SL-RELATIVE-TIME"): node is SlRelativeTime
export function sl_is(node: Element, name: "SL-RESIZE-OBSERVER"): node is SlResizeObserver
export function sl_is(node: Element, name: "SL-SELECT"): node is SlSelect
export function sl_is(node: Element, name: "SL-SKELETON"): node is SlSkeleton
export function sl_is(node: Element, name: "SL-SPINNER"): node is SlSpinner
export function sl_is(node: Element, name: "SL-SPLIT-PANEL"): node is SlSplitPanel
export function sl_is(node: Element, name: "SL-SWITCH"): node is SlSwitch
export function sl_is(node: Element, name: "SL-TAB"): node is SlTab
export function sl_is(node: Element, name: "SL-TAB-PANEL"): node is SlTabPanel
export function sl_is(node: Element, name: "SL-TAB-GROUP"): node is SlTabGroup
export function sl_is(node: Element, name: "SL-TOOLTIP"): node is SlTooltip
export function sl_is(node: Element, name: "SL-TREE"): node is SlTree
export function sl_is(node: Element, name: "SL-TEXTAREA"): node is SlTextarea
export function sl_is(node: Element, name: "SL-TAG"): node is SlTag
export function sl_is(node: Element, name: "SL-TREE-ITEM"): node is SlTreeItem
export function sl_is(node: Element, name: "SL-VISUALLY-HIDDEN"): node is SlVisuallyHidden
export function sl_is(node: any, name: string): boolean {
  return node.tagName === name
}
