
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlAvatar from "@shoelace-style/shoelace/dist/components/avatar/avatar.js"

import { NRO, Attrs } from "elt"

export { SlAvatar }
declare module "elt" {
  interface attrs_sl_avatar extends Attrs<HTMLElementTagNameMap["sl-avatar"]> {
    /** The image source to use for the avatar. */
    image?: NRO<string>
    /** A label to use to describe the avatar to assistive devices. */
    label?: NRO<string>
    /** Initials to use as a fallback when no image is available (1-2 characters max recommended). */
    initials?: NRO<string>
    /** Indicates how the browser should load the image. */
    loading?: NRO<'eager' | 'lazy'>
    /** The shape of the avatar. */
    shape?: NRO<'circle' | 'square' | 'rounded'>
  }

  interface ElementMap {
    "sl-avatar": attrs_sl_avatar
  }

}
