
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlBadge from "@shoelace-style/shoelace/dist/components/badge/badge.js"

import { NRO, Attrs } from "elt"

export { SlBadge }
declare module "elt" {
  interface attrs_sl_badge extends Attrs<HTMLElementTagNameMap["sl-badge"]> {
    /** The badge's theme variant. */
    variant?: NRO<'primary' | 'success' | 'neutral' | 'warning' | 'danger'>
    /** Draws a pill-style badge with rounded edges. */
    pill?: NRO<boolean>
    /** Makes the badge pulsate to draw attention. */
    pulse?: NRO<boolean>
  }

  interface ElementMap {
    "sl-badge": attrs_sl_badge
  }

}
