
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlCard from "@shoelace-style/shoelace/dist/components/card/card.js"

import { Attrs } from "elt"

export { SlCard }
declare module "elt" {
  interface attrs_sl_card extends Attrs<HTMLElementTagNameMap["sl-card"]> {
  }

  interface ElementMap {
    "sl-card": attrs_sl_card
  }

}
