
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlCarouselItem from "@shoelace-style/shoelace/dist/components/carousel-item/carousel-item.js"

import { Attrs } from "elt"

export { SlCarouselItem }
declare module "elt" {
  interface attrs_sl_carousel_item extends Attrs<HTMLElementTagNameMap["sl-carousel-item"]> {
  }

  interface ElementMap {
    "sl-carousel-item": attrs_sl_carousel_item
  }

}
