
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlDivider from "@shoelace-style/shoelace/dist/components/divider/divider.js"

import { NRO, Attrs } from "elt"

export { SlDivider }
declare module "elt" {
  interface attrs_sl_divider extends Attrs<HTMLElementTagNameMap["sl-divider"]> {
    /** Draws the divider in a vertical orientation. */
    vertical?: NRO<boolean>
  }

  interface ElementMap {
    "sl-divider": attrs_sl_divider
  }

}
