
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlImageComparer from "@shoelace-style/shoelace/dist/components/image-comparer/image-comparer.js"

import { NRO, Attrs } from "elt"

export { SlImageComparer }
declare module "elt" {
  interface attrs_sl_image_comparer extends Attrs<HTMLElementTagNameMap["sl-image-comparer"]> {
    /** The position of the divider as a percentage. */
    position?: NRO<number>
  }

  interface ElementMap {
    "sl-image-comparer": attrs_sl_image_comparer
  }

}
