
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlMenu from "@shoelace-style/shoelace/dist/components/menu/menu.js"

import { Attrs } from "elt"

export { SlMenu }
declare module "elt" {
  interface attrs_sl_menu extends Attrs<HTMLElementTagNameMap["sl-menu"]> {
  }

  interface ElementMap {
    "sl-menu": attrs_sl_menu
  }

}
