
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlMenuItem from "@shoelace-style/shoelace/dist/components/menu-item/menu-item.js"

import { NRO, Attrs } from "elt"

export { SlMenuItem }
declare module "elt" {
  interface attrs_sl_menu_item extends Attrs<HTMLElementTagNameMap["sl-menu-item"]> {
    /** The type of menu item to render. To use `checked`, this value must be set to `checkbox`. */
    type?: NRO<'normal' | 'checkbox'>
    /** Draws the item in a checked state. */
    checked?: NRO<boolean>
    /** A unique value to store in the menu item. This can be used as a way to identify menu items when selected. */
    value?: NRO<string>
    /** Draws the menu item in a loading state. */
    loading?: NRO<boolean>
    /** Draws the menu item in a disabled state, preventing selection. */
    disabled?: NRO<boolean>
  }

  interface ElementMap {
    "sl-menu-item": attrs_sl_menu_item
  }

}
