
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlRelativeTime from "@shoelace-style/shoelace/dist/components/relative-time/relative-time.js"

import { NRO, Attrs } from "elt"

export { SlRelativeTime }
declare module "elt" {
  interface attrs_sl_relative_time extends Attrs<HTMLElementTagNameMap["sl-relative-time"]> {
    /** The date from which to calculate time from. If not set, the current date and time will be used. When passing a
string, it's strongly recommended to use the ISO 8601 format to ensure timezones are handled correctly. To convert
a date to this format in JavaScript, use [`date.toISOString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString). */
    date?: NRO<Date | string>
    /** The formatting style to use. */
    format?: NRO<'long' | 'short' | 'narrow'>
    /** When `auto`, values such as "yesterday" and "tomorrow" will be shown when possible. When `always`, values such as
"1 day ago" and "in 1 day" will be shown. */
    numeric?: NRO<'always' | 'auto'>
    /** Keep the displayed value up to date as time passes. */
    sync?: NRO<boolean>
  }

  interface ElementMap {
    "sl-relative-time": attrs_sl_relative_time
  }

}
