
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlSpinner from "@shoelace-style/shoelace/dist/components/spinner/spinner.js"

import { NRO, Attrs } from "elt"

export { SlSpinner }
declare module "elt" {
  interface attrs_sl_spinner extends Attrs<HTMLElementTagNameMap["sl-spinner"]> {
  }

  interface ElementMap {
    "sl-spinner": attrs_sl_spinner
  }

}
