
/**
 * This file is generated by genshoelace.js using the custom-elements.json file provided.
 */
import SlVisuallyHidden from "@shoelace-style/shoelace/dist/components/visually-hidden/visually-hidden.js"

import { NRO, Attrs } from "elt"

export { SlVisuallyHidden }
declare module "elt" {
  interface attrs_sl_visually_hidden extends Attrs<HTMLElementTagNameMap["sl-visually-hidden"]> {
  }

  interface ElementMap {
    "sl-visually-hidden": attrs_sl_visually_hidden
  }

}
