export function cssval(v: "spacing-3x-small"): string
export function cssval(v: "spacing-2x-small"): string
export function cssval(v: "spacing-x-small"): string
export function cssval(v: "spacing-small"): string
export function cssval(v: "spacing-medium"): string
export function cssval(v: "spacing-large"): string
export function cssval(v: "spacing-x-large"): string
export function cssval(v: "spacing-2x-large"): string
export function cssval(v: "spacing-3x-large"): string
export function cssval(v: "spacing-4x-large"): string
export function cssval(v: "color-neutral-0"): string
export function cssval(v: "color-neutral-1000"): string
export function cssval(v: "color-primary-50"): string
export function cssval(v: "color-primary-100"): string
export function cssval(v: "color-primary-200"): string
export function cssval(v: "color-primary-300"): string
export function cssval(v: "color-primary-400"): string
export function cssval(v: "color-primary-500"): string
export function cssval(v: "color-primary-600"): string
export function cssval(v: "color-primary-700"): string
export function cssval(v: "color-primary-800"): string
export function cssval(v: "color-primary-900"): string
export function cssval(v: "color-primary-950"): string
export function cssval(v: "color-success-50"): string
export function cssval(v: "color-success-100"): string
export function cssval(v: "color-success-200"): string
export function cssval(v: "color-success-300"): string
export function cssval(v: "color-success-400"): string
export function cssval(v: "color-success-500"): string
export function cssval(v: "color-success-600"): string
export function cssval(v: "color-success-700"): string
export function cssval(v: "color-success-800"): string
export function cssval(v: "color-success-900"): string
export function cssval(v: "color-success-950"): string
export function cssval(v: "color-warning-50"): string
export function cssval(v: "color-warning-100"): string
export function cssval(v: "color-warning-200"): string
export function cssval(v: "color-warning-300"): string
export function cssval(v: "color-warning-400"): string
export function cssval(v: "color-warning-500"): string
export function cssval(v: "color-warning-600"): string
export function cssval(v: "color-warning-700"): string
export function cssval(v: "color-warning-800"): string
export function cssval(v: "color-warning-900"): string
export function cssval(v: "color-warning-950"): string
export function cssval(v: "color-danger-50"): string
export function cssval(v: "color-danger-100"): string
export function cssval(v: "color-danger-200"): string
export function cssval(v: "color-danger-300"): string
export function cssval(v: "color-danger-400"): string
export function cssval(v: "color-danger-500"): string
export function cssval(v: "color-danger-600"): string
export function cssval(v: "color-danger-700"): string
export function cssval(v: "color-danger-800"): string
export function cssval(v: "color-danger-900"): string
export function cssval(v: "color-danger-950"): string
export function cssval(v: "color-neutral-50"): string
export function cssval(v: "color-neutral-100"): string
export function cssval(v: "color-neutral-200"): string
export function cssval(v: "color-neutral-300"): string
export function cssval(v: "color-neutral-400"): string
export function cssval(v: "color-neutral-500"): string
export function cssval(v: "color-neutral-600"): string
export function cssval(v: "color-neutral-700"): string
export function cssval(v: "color-neutral-800"): string
export function cssval(v: "color-neutral-900"): string
export function cssval(v: "color-neutral-950"): string
export function cssval(v: "color-gray-50"): string
export function cssval(v: "color-gray-100"): string
export function cssval(v: "color-gray-200"): string
export function cssval(v: "color-gray-300"): string
export function cssval(v: "color-gray-400"): string
export function cssval(v: "color-gray-500"): string
export function cssval(v: "color-gray-600"): string
export function cssval(v: "color-gray-700"): string
export function cssval(v: "color-gray-800"): string
export function cssval(v: "color-gray-900"): string
export function cssval(v: "color-gray-950"): string
export function cssval(v: "color-red-50"): string
export function cssval(v: "color-red-100"): string
export function cssval(v: "color-red-200"): string
export function cssval(v: "color-red-300"): string
export function cssval(v: "color-red-400"): string
export function cssval(v: "color-red-500"): string
export function cssval(v: "color-red-600"): string
export function cssval(v: "color-red-700"): string
export function cssval(v: "color-red-800"): string
export function cssval(v: "color-red-900"): string
export function cssval(v: "color-red-950"): string
export function cssval(v: "color-orange-50"): string
export function cssval(v: "color-orange-100"): string
export function cssval(v: "color-orange-200"): string
export function cssval(v: "color-orange-300"): string
export function cssval(v: "color-orange-400"): string
export function cssval(v: "color-orange-500"): string
export function cssval(v: "color-orange-600"): string
export function cssval(v: "color-orange-700"): string
export function cssval(v: "color-orange-800"): string
export function cssval(v: "color-orange-900"): string
export function cssval(v: "color-orange-950"): string
export function cssval(v: "color-amber-50"): string
export function cssval(v: "color-amber-100"): string
export function cssval(v: "color-amber-200"): string
export function cssval(v: "color-amber-300"): string
export function cssval(v: "color-amber-400"): string
export function cssval(v: "color-amber-500"): string
export function cssval(v: "color-amber-600"): string
export function cssval(v: "color-amber-700"): string
export function cssval(v: "color-amber-800"): string
export function cssval(v: "color-amber-900"): string
export function cssval(v: "color-amber-950"): string
export function cssval(v: "color-yellow-50"): string
export function cssval(v: "color-yellow-100"): string
export function cssval(v: "color-yellow-200"): string
export function cssval(v: "color-yellow-300"): string
export function cssval(v: "color-yellow-400"): string
export function cssval(v: "color-yellow-500"): string
export function cssval(v: "color-yellow-600"): string
export function cssval(v: "color-yellow-700"): string
export function cssval(v: "color-yellow-800"): string
export function cssval(v: "color-yellow-900"): string
export function cssval(v: "color-yellow-950"): string
export function cssval(v: "color-lime-50"): string
export function cssval(v: "color-lime-100"): string
export function cssval(v: "color-lime-200"): string
export function cssval(v: "color-lime-300"): string
export function cssval(v: "color-lime-400"): string
export function cssval(v: "color-lime-500"): string
export function cssval(v: "color-lime-600"): string
export function cssval(v: "color-lime-700"): string
export function cssval(v: "color-lime-800"): string
export function cssval(v: "color-lime-900"): string
export function cssval(v: "color-lime-950"): string
export function cssval(v: "color-green-50"): string
export function cssval(v: "color-green-100"): string
export function cssval(v: "color-green-200"): string
export function cssval(v: "color-green-300"): string
export function cssval(v: "color-green-400"): string
export function cssval(v: "color-green-500"): string
export function cssval(v: "color-green-600"): string
export function cssval(v: "color-green-700"): string
export function cssval(v: "color-green-800"): string
export function cssval(v: "color-green-900"): string
export function cssval(v: "color-green-950"): string
export function cssval(v: "color-emerald-50"): string
export function cssval(v: "color-emerald-100"): string
export function cssval(v: "color-emerald-200"): string
export function cssval(v: "color-emerald-300"): string
export function cssval(v: "color-emerald-400"): string
export function cssval(v: "color-emerald-500"): string
export function cssval(v: "color-emerald-600"): string
export function cssval(v: "color-emerald-700"): string
export function cssval(v: "color-emerald-800"): string
export function cssval(v: "color-emerald-900"): string
export function cssval(v: "color-emerald-950"): string
export function cssval(v: "color-teal-50"): string
export function cssval(v: "color-teal-100"): string
export function cssval(v: "color-teal-200"): string
export function cssval(v: "color-teal-300"): string
export function cssval(v: "color-teal-400"): string
export function cssval(v: "color-teal-500"): string
export function cssval(v: "color-teal-600"): string
export function cssval(v: "color-teal-700"): string
export function cssval(v: "color-teal-800"): string
export function cssval(v: "color-teal-900"): string
export function cssval(v: "color-teal-950"): string
export function cssval(v: "color-cyan-50"): string
export function cssval(v: "color-cyan-100"): string
export function cssval(v: "color-cyan-200"): string
export function cssval(v: "color-cyan-300"): string
export function cssval(v: "color-cyan-400"): string
export function cssval(v: "color-cyan-500"): string
export function cssval(v: "color-cyan-600"): string
export function cssval(v: "color-cyan-700"): string
export function cssval(v: "color-cyan-800"): string
export function cssval(v: "color-cyan-900"): string
export function cssval(v: "color-cyan-950"): string
export function cssval(v: "color-sky-50"): string
export function cssval(v: "color-sky-100"): string
export function cssval(v: "color-sky-200"): string
export function cssval(v: "color-sky-300"): string
export function cssval(v: "color-sky-400"): string
export function cssval(v: "color-sky-500"): string
export function cssval(v: "color-sky-600"): string
export function cssval(v: "color-sky-700"): string
export function cssval(v: "color-sky-800"): string
export function cssval(v: "color-sky-900"): string
export function cssval(v: "color-sky-950"): string
export function cssval(v: "color-blue-50"): string
export function cssval(v: "color-blue-100"): string
export function cssval(v: "color-blue-200"): string
export function cssval(v: "color-blue-300"): string
export function cssval(v: "color-blue-400"): string
export function cssval(v: "color-blue-500"): string
export function cssval(v: "color-blue-600"): string
export function cssval(v: "color-blue-700"): string
export function cssval(v: "color-blue-800"): string
export function cssval(v: "color-blue-900"): string
export function cssval(v: "color-blue-950"): string
export function cssval(v: "color-indigo-50"): string
export function cssval(v: "color-indigo-100"): string
export function cssval(v: "color-indigo-200"): string
export function cssval(v: "color-indigo-300"): string
export function cssval(v: "color-indigo-400"): string
export function cssval(v: "color-indigo-500"): string
export function cssval(v: "color-indigo-600"): string
export function cssval(v: "color-indigo-700"): string
export function cssval(v: "color-indigo-800"): string
export function cssval(v: "color-indigo-900"): string
export function cssval(v: "color-indigo-950"): string
export function cssval(v: "color-violet-50"): string
export function cssval(v: "color-violet-100"): string
export function cssval(v: "color-violet-200"): string
export function cssval(v: "color-violet-300"): string
export function cssval(v: "color-violet-400"): string
export function cssval(v: "color-violet-500"): string
export function cssval(v: "color-violet-600"): string
export function cssval(v: "color-violet-700"): string
export function cssval(v: "color-violet-800"): string
export function cssval(v: "color-violet-900"): string
export function cssval(v: "color-violet-950"): string
export function cssval(v: "color-purple-50"): string
export function cssval(v: "color-purple-100"): string
export function cssval(v: "color-purple-200"): string
export function cssval(v: "color-purple-300"): string
export function cssval(v: "color-purple-400"): string
export function cssval(v: "color-purple-500"): string
export function cssval(v: "color-purple-600"): string
export function cssval(v: "color-purple-700"): string
export function cssval(v: "color-purple-800"): string
export function cssval(v: "color-purple-900"): string
export function cssval(v: "color-purple-950"): string
export function cssval(v: "color-fuchsia-50"): string
export function cssval(v: "color-fuchsia-100"): string
export function cssval(v: "color-fuchsia-200"): string
export function cssval(v: "color-fuchsia-300"): string
export function cssval(v: "color-fuchsia-400"): string
export function cssval(v: "color-fuchsia-500"): string
export function cssval(v: "color-fuchsia-600"): string
export function cssval(v: "color-fuchsia-700"): string
export function cssval(v: "color-fuchsia-800"): string
export function cssval(v: "color-fuchsia-900"): string
export function cssval(v: "color-fuchsia-950"): string
export function cssval(v: "color-pink-50"): string
export function cssval(v: "color-pink-100"): string
export function cssval(v: "color-pink-200"): string
export function cssval(v: "color-pink-300"): string
export function cssval(v: "color-pink-400"): string
export function cssval(v: "color-pink-500"): string
export function cssval(v: "color-pink-600"): string
export function cssval(v: "color-pink-700"): string
export function cssval(v: "color-pink-800"): string
export function cssval(v: "color-pink-900"): string
export function cssval(v: "color-pink-950"): string
export function cssval(v: "color-rose-50"): string
export function cssval(v: "color-rose-100"): string
export function cssval(v: "color-rose-200"): string
export function cssval(v: "color-rose-300"): string
export function cssval(v: "color-rose-400"): string
export function cssval(v: "color-rose-500"): string
export function cssval(v: "color-rose-600"): string
export function cssval(v: "color-rose-700"): string
export function cssval(v: "color-rose-800"): string
export function cssval(v: "color-rose-900"): string
export function cssval(v: "color-rose-950"): string
export function cssval(v: "transition-x-slow"): string
export function cssval(v: "transition-slow"): string
export function cssval(v: "transition-medium"): string
export function cssval(v: "transition-fast"): string
export function cssval(v: "transition-x-fast"): string
export function cssval(v: "border-radius-small"): string
export function cssval(v: "border-radius-medium"): string
export function cssval(v: "border-radius-large"): string
export function cssval(v: "border-radius-x-large"): string
export function cssval(v: "border-radius-circle"): string
export function cssval(v: "border-radius-pill"): string
export function cssval(v: "shadow-x-small"): string
export function cssval(v: "shadow-small"): string
export function cssval(v: "shadow-medium"): string
export function cssval(v: "shadow-large"): string
export function cssval(v: "shadow-x-large"): string
export function cssval(s: string): string {
  return `var(--sl-${s})`
}
